version: "3.8"

volumes:
  tmp:
    name: tmp-$PORT-$ROBOT_NAME_1

services:
  webots:
    image: simulation
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE=$IMAGE
#    command: /usr/local/webots/webots --port=$PORT --stream="monitorActivity" --batch --mode=realtime --minimize --no-rendering $WORLD
    command: ls /usr/local
    environment:
      - DISPLAY=:0
    ports:
      - '$PORT:$PORT'
    privileged: true
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - tmp:/tmp/webots-$PORT/$ROBOT_NAME_1
