ifeq ($(OS),Windows_NT)
TARGET = client.exe
LIBS = -lws2_32
CXX=g++
else
TARGET = client
LIBS =
endif
ifeq ($(MAKECMDGOALS),)
GOAL = release
else
GOAL = $(MAKECMDGOALS)
endif

LIBS += `pkg-config --cflags --libs protobuf`

.PHONY = build release debug profile

build release debug profile: $(TARGET)

$(TARGET): client.cpp
	$(CXX) $< build/$(GOAL)/messages.pb.o -o $@ $(LIBS)

clean:
	rm -f client.o client client.exe
