ifeq ($(OS),Windows_NT)
TARGET = client.exe
LIBS=-lws2_32
CC=gcc
else
TARGET = client
LIBS=
endif

.PHONY = build release debug profile

build release debug profile: $(TARGET)

$(TARGET): client.c
	$(CC) $(CFLAGS) $< -o $@ $(LIBS)

clean:
	rm -f client.o client client.exe
