import {VRML} from './utility/utility.js';

export const ProtoModel = {
  'ProtoCylinder': {'myRadiusRadius': VRML.SFFloat, 'myHeightHeight': VRML.SFFloat},
  'TinkerbotsPlasticAppearance': {'color': VRML.SFString, 'occlusionMapUrl': VRML.MFString},
  'TinkerbotsAxle': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'endSlot': VRML.SFNode, 'length': VRML.SFString},
  'TinkerbotsBase': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'controller': VRML.SFString, 'controllerArgs': VRML.MFString, 'customData': VRML.SFString, 'supervisor': VRML.SFBool, 'synchronization': VRML.SFBool, 'selfCollision': VRML.SFBool, 'upSlot': VRML.SFNode, 'upASlot': VRML.SFNode, 'upBSlot': VRML.SFNode, 'upCSlot': VRML.SFNode, 'upDSlot': VRML.SFNode, 'downSlot': VRML.SFNode, 'downASlot': VRML.SFNode, 'downBSlot': VRML.SFNode, 'downCSlot': VRML.SFNode, 'downDSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'leftASlot': VRML.SFNode, 'leftBSlot': VRML.SFNode, 'leftCSlot': VRML.SFNode, 'leftDSlot': VRML.SFNode, 'rightSlot': VRML.SFNode, 'rightASlot': VRML.SFNode, 'rightBSlot': VRML.SFNode, 'rightCSlot': VRML.SFNode, 'rightDSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'backASlot': VRML.SFNode, 'backBSlot': VRML.SFNode, 'backCSlot': VRML.SFNode, 'backDSlot': VRML.SFNode, 'extensionSlot': VRML.MFNode},
  'TinkerbotsBrickAdapter': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString},
  'TinkerbotsCube': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'upASlot': VRML.SFNode, 'upBSlot': VRML.SFNode, 'upCSlot': VRML.SFNode, 'upDSlot': VRML.SFNode, 'downSlot': VRML.SFNode, 'downASlot': VRML.SFNode, 'downBSlot': VRML.SFNode, 'downCSlot': VRML.SFNode, 'downDSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'leftASlot': VRML.SFNode, 'leftBSlot': VRML.SFNode, 'leftCSlot': VRML.SFNode, 'leftDSlot': VRML.SFNode, 'rightSlot': VRML.SFNode, 'rightASlot': VRML.SFNode, 'rightBSlot': VRML.SFNode, 'rightCSlot': VRML.SFNode, 'rightDSlot': VRML.SFNode, 'frontSlot': VRML.SFNode, 'frontASlot': VRML.SFNode, 'frontBSlot': VRML.SFNode, 'frontCSlot': VRML.SFNode, 'frontDSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'backASlot': VRML.SFNode, 'backBSlot': VRML.SFNode, 'backCSlot': VRML.SFNode, 'backDSlot': VRML.SFNode},
  'TinkerbotsCubieBoxWithCrossSlots': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'frontSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'rightSlot': VRML.SFNode},
  'TinkerbotsCubieBoxWithRoundSlots': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'frontSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'axisSlot': VRML.SFNode},
  'TinkerbotsCubieFemaleCube': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'frontSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'rightSlot': VRML.SFNode},
  'TinkerbotsCubieMaleCube': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'frontSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'rightSlot': VRML.SFNode},
  'TinkerbotsCubiePyramid': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'color': VRML.SFString, 'frontSlot': VRML.SFNode, 'backSlot': VRML.SFNode},
  'TinkerbotsDistanceSensor': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'numberOfRays': VRML.SFInt32, 'aperture': VRML.SFFloat, 'upSlot': VRML.SFNode, 'upASlot': VRML.SFNode, 'upBSlot': VRML.SFNode, 'upCSlot': VRML.SFNode, 'upDSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'leftASlot': VRML.SFNode, 'leftBSlot': VRML.SFNode, 'leftCSlot': VRML.SFNode, 'leftDSlot': VRML.SFNode, 'rightSlot': VRML.SFNode, 'rightASlot': VRML.SFNode, 'rightBSlot': VRML.SFNode, 'rightCSlot': VRML.SFNode, 'rightDSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'backASlot': VRML.SFNode, 'backBSlot': VRML.SFNode, 'backCSlot': VRML.SFNode, 'backDSlot': VRML.SFNode},
  'TinkerbotsFinger': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString},
  'TinkerbotsGrabber': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'fingerASlot': VRML.SFNode, 'fingerBSlot': VRML.SFNode, 'fingerCSlot': VRML.SFNode},
  'TinkerbotsLEDAppearance': {},
  'TinkerbotsLightSensor': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'upASlot': VRML.SFNode, 'upBSlot': VRML.SFNode, 'upCSlot': VRML.SFNode, 'upDSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'leftASlot': VRML.SFNode, 'leftBSlot': VRML.SFNode, 'leftCSlot': VRML.SFNode, 'leftDSlot': VRML.SFNode, 'rightSlot': VRML.SFNode, 'rightASlot': VRML.SFNode, 'rightBSlot': VRML.SFNode, 'rightCSlot': VRML.SFNode, 'rightDSlot': VRML.SFNode, 'backSlot': VRML.SFNode, 'backASlot': VRML.SFNode, 'backBSlot': VRML.SFNode, 'backCSlot': VRML.SFNode, 'backDSlot': VRML.SFNode},
  'TinkerbotsMotor': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'upSlot': VRML.SFNode, 'upASlot': VRML.SFNode, 'upBSlot': VRML.SFNode, 'upCSlot': VRML.SFNode, 'upDSlot': VRML.SFNode, 'leftSlot': VRML.SFNode, 'leftASlot': VRML.SFNode, 'leftBSlot': VRML.SFNode, 'leftCSlot': VRML.SFNode, 'leftDSlot': VRML.SFNode, 'rightSlot': VRML.SFNode, 'rightASlot': VRML.SFNode, 'rightBSlot': VRML.SFNode, 'rightCSlot': VRML.SFNode, 'rightDSlot': VRML.SFNode, 'frontSlot': VRML.SFNode, 'backSlot': VRML.SFNode},
  'TinkerbotsPivot': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'slot': VRML.SFNode, 'ASlot': VRML.SFNode, 'BSlot': VRML.SFNode, 'CSlot': VRML.SFNode, 'DSlot': VRML.SFNode},
  'TinkerbotsTwister': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString, 'slot': VRML.SFNode, 'ASlot': VRML.SFNode, 'BSlot': VRML.SFNode, 'CSlot': VRML.SFNode, 'DSlot': VRML.SFNode},
  'TinkerbotsWheel': {'translation': VRML.SFVec3f, 'rotation': VRML.SFRotation, 'name': VRML.SFString}
};
