version: "3.8"

volumes:
  tmp:
    name: tmp-$PORT

services:
  webots:
    image: simulation
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WEBOTS_DEFAULT_IMAGE=$IMAGE
    command: webots --stream="port=$PORT;monitorActivity" --batch --mode=realtime --minimize --no-rendering $WORLD
    environment:
      - DISPLAY=:0
    ports:
      - '$PORT:$PORT'
    privileged: true
    stdin_open: true  # docker run -i
    tty: true         # docker run -t
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - tmp:/tmp
