/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class AnsiCodes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AnsiCodes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AnsiCodes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_AnsiCodes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public final static String RESET = "\u001b[0m";

  public final static String BOLD = "\u001b[1m";
  public final static String UNDERLINE = "\u001b[4m";

  public final static String BLACK_BACKGROUND = "\u001b[40m";
  public final static String RED_BACKGROUND = "\u001b[41m";
  public final static String GREEN_BACKGROUND = "\u001b[42m";
  public final static String YELLOW_BACKGROUND = "\u001b[43m";
  public final static String BLUE_BACKGROUND = "\u001b[44m";
  public final static String MAGENTA_BACKGROUND = "\u001b[45m";
  public final static String CYAN_BACKGROUND = "\u001b[46m";
  public final static String WHITE_BACKGROUND = "\u001b[47m";

  public final static String BLACK_FOREGROUND = "\u001b[30m";
  public final static String RED_FOREGROUND = "\u001b[31m";
  public final static String GREEN_FOREGROUND = "\u001b[32m";
  public final static String YELLOW_FOREGROUND = "\u001b[33m";
  public final static String BLUE_FOREGROUND = "\u001b[34m";
  public final static String MAGENTA_FOREGROUND = "\u001b[35m";
  public final static String CYAN_FOREGROUND = "\u001b[36m";
  public final static String WHITE_FOREGROUND = "\u001b[37m";

  public final static String CLEAR_SCREEN = "\u001b[2J";

  public AnsiCodes() {
    this(wrapperJNI.new_AnsiCodes(), true);
  }

}
