/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Compass extends Device {
  private transient long swigCPtr;

  protected Compass(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.Compass_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Compass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_Compass(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Compass(String name) {
    this(wrapperJNI.new_Compass(name), true);
  }

  public void enable(int samplingPeriod) {
    wrapperJNI.Compass_enable(swigCPtr, this, samplingPeriod);
  }

  public void disable() {
    wrapperJNI.Compass_disable(swigCPtr, this);
  }

  public int getSamplingPeriod() {
    return wrapperJNI.Compass_getSamplingPeriod(swigCPtr, this);
  }

  public double[] getValues() {
    return wrapperJNI.Compass_getValues(swigCPtr, this);
  }

  private int getLookupTableSize() {
    return wrapperJNI.Compass_getLookupTableSize(swigCPtr, this);
  }

  public double[] getLookupTable() {
    return wrapperJNI.Compass_getLookupTable(swigCPtr, this);
  }

}
