/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Device {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Device(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_Device(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return wrapperJNI.Device_getName(swigCPtr, this);
  }

  public String getModel() {
    return wrapperJNI.Device_getModel(swigCPtr, this);
  }

  public int getNodeType() {
    return wrapperJNI.Device_getNodeType(swigCPtr, this);
  }

  public int getTag() {
    return wrapperJNI.Device_getTag(swigCPtr, this);
  }

  public static boolean hasType(int tag, int type) {
    return wrapperJNI.Device_hasType(tag, type);
  }

}
