/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class DistanceSensor extends Device {
  private transient long swigCPtr;

  protected DistanceSensor(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.DistanceSensor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DistanceSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_DistanceSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DistanceSensor(String name) {
    this(wrapperJNI.new_DistanceSensor(name), true);
  }

  public void enable(int samplingPeriod) {
    wrapperJNI.DistanceSensor_enable(swigCPtr, this, samplingPeriod);
  }

  public void disable() {
    wrapperJNI.DistanceSensor_disable(swigCPtr, this);
  }

  public int getSamplingPeriod() {
    return wrapperJNI.DistanceSensor_getSamplingPeriod(swigCPtr, this);
  }

  public double getValue() {
    return wrapperJNI.DistanceSensor_getValue(swigCPtr, this);
  }

  public double getMaxValue() {
    return wrapperJNI.DistanceSensor_getMaxValue(swigCPtr, this);
  }

  public double getMinValue() {
    return wrapperJNI.DistanceSensor_getMinValue(swigCPtr, this);
  }

  public double getAperture() {
    return wrapperJNI.DistanceSensor_getAperture(swigCPtr, this);
  }

  private int getLookupTableSize() {
    return wrapperJNI.DistanceSensor_getLookupTableSize(swigCPtr, this);
  }

  public double[] getLookupTable() {
    return wrapperJNI.DistanceSensor_getLookupTable(swigCPtr, this);
  }

  public int getType() {
    return wrapperJNI.DistanceSensor_getType(swigCPtr, this);
  }

  // Type 
  public final static int GENERIC = 0;
  public final static int INFRA_RED = GENERIC + 1;
  public final static int SONAR = INFRA_RED + 1;
  public final static int LASER = SONAR + 1;

}
