/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class ImageRef {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImageRef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_ImageRef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ImageRef(SWIGTYPE_p_WbImageRef imageRef) {
    this(wrapperJNI.new_ImageRef(SWIGTYPE_p_WbImageRef.getCPtr(imageRef)), true);
  }

}
