/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class InertialUnit extends Device {
  private transient long swigCPtr;

  protected InertialUnit(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.InertialUnit_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InertialUnit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_InertialUnit(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public InertialUnit(String name) {
    this(wrapperJNI.new_InertialUnit(name), true);
  }

  public void enable(int samplingPeriod) {
    wrapperJNI.InertialUnit_enable(swigCPtr, this, samplingPeriod);
  }

  public void disable() {
    wrapperJNI.InertialUnit_disable(swigCPtr, this);
  }

  public int getSamplingPeriod() {
    return wrapperJNI.InertialUnit_getSamplingPeriod(swigCPtr, this);
  }

  public double[] getRollPitchYaw() {
    return wrapperJNI.InertialUnit_getRollPitchYaw(swigCPtr, this);
  }

  private int getLookupTableSize() {
    return wrapperJNI.InertialUnit_getLookupTableSize(swigCPtr, this);
  }

  public double[] getLookupTable() {
    return wrapperJNI.InertialUnit_getLookupTable(swigCPtr, this);
  }

}
