/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class LightSensor extends Device {
  private transient long swigCPtr;

  protected LightSensor(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.LightSensor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LightSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_LightSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LightSensor(String name) {
    this(wrapperJNI.new_LightSensor(name), true);
  }

  public void enable(int samplingPeriod) {
    wrapperJNI.LightSensor_enable(swigCPtr, this, samplingPeriod);
  }

  public void disable() {
    wrapperJNI.LightSensor_disable(swigCPtr, this);
  }

  public int getSamplingPeriod() {
    return wrapperJNI.LightSensor_getSamplingPeriod(swigCPtr, this);
  }

  public double getValue() {
    return wrapperJNI.LightSensor_getValue(swigCPtr, this);
  }

  private int getLookupTableSize() {
    return wrapperJNI.LightSensor_getLookupTableSize(swigCPtr, this);
  }

  public double[] getLookupTable() {
    return wrapperJNI.LightSensor_getLookupTable(swigCPtr, this);
  }

}
