/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class MouseState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MouseState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MouseState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_MouseState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLeft(boolean value) {
    wrapperJNI.MouseState_left_set(swigCPtr, this, value);
  }

  public boolean getLeft() {
    return wrapperJNI.MouseState_left_get(swigCPtr, this);
  }

  public void setMiddle(boolean value) {
    wrapperJNI.MouseState_middle_set(swigCPtr, this, value);
  }

  public boolean getMiddle() {
    return wrapperJNI.MouseState_middle_get(swigCPtr, this);
  }

  public void setRight(boolean value) {
    wrapperJNI.MouseState_right_set(swigCPtr, this, value);
  }

  public boolean getRight() {
    return wrapperJNI.MouseState_right_get(swigCPtr, this);
  }

  public void setU(double value) {
    wrapperJNI.MouseState_u_set(swigCPtr, this, value);
  }

  public double getU() {
    return wrapperJNI.MouseState_u_get(swigCPtr, this);
  }

  public void setV(double value) {
    wrapperJNI.MouseState_v_set(swigCPtr, this, value);
  }

  public double getV() {
    return wrapperJNI.MouseState_v_get(swigCPtr, this);
  }

  public void setX(double value) {
    wrapperJNI.MouseState_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return wrapperJNI.MouseState_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    wrapperJNI.MouseState_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return wrapperJNI.MouseState_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    wrapperJNI.MouseState_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return wrapperJNI.MouseState_z_get(swigCPtr, this);
  }

  public MouseState() {
    this(wrapperJNI.new_MouseState(), true);
  }

}
