/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class Pen extends Device {
  private transient long swigCPtr;

  protected Pen(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.Pen_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pen obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_Pen(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Pen(String name) {
    this(wrapperJNI.new_Pen(name), true);
  }

  public void write(boolean write) {
    wrapperJNI.Pen_write(swigCPtr, this, write);
  }

  public void setInkColor(int color, double density) {
    wrapperJNI.Pen_setInkColor(swigCPtr, this, color, density);
  }

}
