/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cyberbotics.webots.controller;

public class PositionSensor extends Device {
  private transient long swigCPtr;

  protected PositionSensor(long cPtr, boolean cMemoryOwn) {
    super(wrapperJNI.PositionSensor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PositionSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wrapperJNI.delete_PositionSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  private Brake brake;
  private Motor motor;

  public Brake getBrake() {
    if (brake == null)
      brake = (Brake)Robot.getDevice(getBrakeTag());
    return brake;
  }
  public Motor getMotor() {
    if (motor == null)
      motor = (Motor)Robot.getDevice(getMotorTag());
    return motor;
  }

  public PositionSensor(String name) {
    this(wrapperJNI.new_PositionSensor(name), true);
  }

  public void enable(int samplingPeriod) {
    wrapperJNI.PositionSensor_enable(swigCPtr, this, samplingPeriod);
  }

  public void disable() {
    wrapperJNI.PositionSensor_disable(swigCPtr, this);
  }

  public int getSamplingPeriod() {
    return wrapperJNI.PositionSensor_getSamplingPeriod(swigCPtr, this);
  }

  public double getValue() {
    return wrapperJNI.PositionSensor_getValue(swigCPtr, this);
  }

  public int getType() {
    return wrapperJNI.PositionSensor_getType(swigCPtr, this);
  }

  private Brake getBrakePrivate() {
    long cPtr = wrapperJNI.PositionSensor_getBrakePrivate(swigCPtr, this);
    return (cPtr == 0) ? null : new Brake(cPtr, false);
  }

  private Motor getMotorPrivate() {
    long cPtr = wrapperJNI.PositionSensor_getMotorPrivate(swigCPtr, this);
    return (cPtr == 0) ? null : new Motor(cPtr, false);
  }

  public int getBrakeTag() {
    return wrapperJNI.PositionSensor_getBrakeTag(swigCPtr, this);
  }

  public int getMotorTag() {
    return wrapperJNI.PositionSensor_getMotorTag(swigCPtr, this);
  }

  // Type 
  public final static int ROTATIONAL = 0;
  public final static int LINEAR = ROTATIONAL + 1;

  public final static int ANGULAR = 0;

}
