#ifndef WR_GLSL_LAYOUT_H
#define WR_GLSL_LAYOUT_H

#ifdef __cplusplus
extern "C" {
#endif

/* For indexing into gUniformNames */
typedef enum WrGlslLayoutUniform {
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE0,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE1,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE2,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE3,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE4,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE5,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE6,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE7,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE8,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE9,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE10,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE11,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE12,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE_CUBE0,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE_CUBE1,
  WR_GLSL_LAYOUT_UNIFORM_ITERATION_NUMBER,
  WR_GLSL_LAYOUT_UNIFORM_MODEL_TRANSFORM,
  WR_GLSL_LAYOUT_UNIFORM_TEXTURE_TRANSFORM,
  WR_GLSL_LAYOUT_UNIFORM_VIEWPORT_SIZE,
  WR_GLSL_LAYOUT_UNIFORM_COLOR_PER_VERTEX,
  WR_GLSL_LAYOUT_UNIFORM_POINT_SIZE,
  WR_GLSL_LAYOUT_UNIFORM_CHANNEL_COUNT,
  WR_GLSL_LAYOUT_UNIFORM_GTAO,
  WR_GLSL_LAYOUT_UNIFORM_COUNT
} WrGlslLayoutUniform;

/* For indexing into gUniformBufferNames and gUniformBufferSizes */
typedef enum WrGlslLayoutUniformBuffer {
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_MATERIAL_PHONG,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_MATERIAL_PBR,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_LIGHTS,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_LIGHT_RENDERABLE,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_CAMERA_TRANSFORMS,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_FOG,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_OVERLAY,
  WR_GLSL_LAYOUT_UNIFORM_BUFFER_COUNT
} WrGlslLayoutUniformBuffer;

#ifdef __cplusplus
}
#endif

#endif  // WR_GLSL_LAYOUT_H
